### ISSUE TITLE
ChangeTip Bot Name

### ISSUE THREAD

**Issue by wbnns** [changecoin/changetip-slack#1]
Any way to make it so that Slack doesn't called ChangeTip "outgoing-webhook" - ?

BTW, this is incredible. Love it. Kudos you all.

![screenshot 2015-03-27 16 25 31](https://cloud.githubusercontent.com/assets/1130872/6878112/0d147240-d49e-11e4-94b3-ae5f165677c9.png)

**Comment by TechNickAI** [comment]
Yep, when you set up the webhook integration you can name it by changing the section called `Customize Name`. We call ours "changetip-bot"

![screen shot 2015-03-27 at 3 31 22 pm](https://cloud.githubusercontent.com/assets/142708/6878181/696370da-d496-11e4-82d9-997628d82cf1.png)

Now have a beer via @changetip on github!

**Comment by changetip** [comment]
Hi @coderwill, @gorillamania sent you a Bitcoin tip worth a beer (14,024 bits/$3.50), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/673274)**.

**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by wbnns** [comment]
Awesome, thanks so much for the fast reply, Nick! For some reason the first
time I added it in Configurations it didn't stick. All good now! Hope you
have a great weekend!

## 

// will binns
// gpg fingerprint: 4519 7EB7 66A7 CC5E 4E66 F200 AF5C 2D1C E58E B37C
// threema id: 5YM2J894

**Comment by TechNickAI** [comment]
I've had some funky issues with slack forms saving properly, that's probably it.

**Comment by wbnns** [comment]
10-4, thanks again @gorillamania - please have a drink on me this weekend! cc @changetip

**Comment by changetip** [comment]
Hi @gorillamania, I've delivered a Bitcoin tip worth a drink (20,130 bits/$5.00) from @coderwill to your ChangeTip wallet.

**[Learn about ChangeTip](https://www.changetip.com/tip-online/github)**
